config/routes.rb
Rails.application.routes.draw do



root "pages#index"
resources :pages
 resources :users
 resources :images
 resources :sessions, only: [:new, :create]
 delete "/logout" => "sessions#destroy", as: :logout

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user

    has_attached_file :file,
      styles: {medium: "300x300>", thumb: "100x100>"},
      default_url: "/images/:style/missing.png"
  
    validates_attachment_content_type :file, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :images, dependent: :destroy
    validates :name, presence: true
    validates :username, presence: true
    validates :username, uniqueness: true
    validates :email, presence:true
    validates :email, uniqueness: true
    validates :password, length: { in: 6..20 }

    def self.search(search)                                                                                               #Search method to declare which fields the method should search for matching queries.
        where("name ILIKE ? OR username ILIKE ?", "%#{search}%", "%#{search}%")     #Used ILIKE(postgres/heroku friendly) instead of LIKE (sql)
      end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    return @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def authorize
    redirect_to new_session_path unless logged_in?
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all.order("created_at DESC")
  end

  def show
    @image = Image.find(params[:id])
    @user = User.find @image.user_id
  end

  def new
    @image = current_user.images.new
  end

  def create
    @image = current_user.images.new image_params
    @image.save
    redirect_to image_path(@image.id)
  end

  def edit
    
    @image = Image.find(params[:id])
    @user = User.find @image.user_id
    if @user != current_user
      redirect_to images_path
    end
  end

  def update
    @image = Image.find(params[:id])
    @image.image_url = params[:image][:image_url]
    @image.date = params[:image][:date]
    @image.title = params[:image][:title]
    @image.description = params[:image][:description]
    @image.category = params[:image][:category]
    @image.save
    redirect_to image_path(@image.id)
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to user_path(@image.user_id)
  end

  private
  def image_params
    return params.require(:image).permit(:file, :date, :title, :description, :category)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @images = Image.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user and @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to images_path
    else
      flash[:warning] = "Check your email and password."
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
    if params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
    else
      @users = User.all.order("created_at DESC")
    end
  end

  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:warning] = "Check your email and password."
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find params[:id]
    if @user != current_user
      redirect_to images_path
    end
  end

  def update
    @user = User.find params[:id]
    @user.name = params[:user][:name]
    @user.username = params[:user][:username]
    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]
    @user.save
    redirect_to user_path
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private
  def user_params
    return params.require(:user).permit(:name, :email, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/images/destroy.html.erb
<h1>Images#destroy</h1>
<p>Find me in app/views/images/destroy.html.erb</p>

app/views/images/edit.html.erb
<div class="row">
    <div class="col-md-6 offset-md-3 edit-background">
      <h1>Edit Image</h1>
      <%= form_for @image do |f| %>
        <div class="form-group">
          <label>Image URL</label>
          <%= f.file_field :file, class: "form-control", placeholder: "Enter URL" %>
        </div>
        <div class="form-group">
          <label>Date</label>
          <%= f.text_field :date, class: "form-control", placeholder: "Enter Date" %>
        </div>
        <div class="form-group">
          <label>Title</label>
          <%= f.text_field :title, class: "form-control", placeholder: "Enter Title" %>
        </div>
        <div class="form-group">
          <label>Description</label>
          <%= f.text_field :description, class: "form-control", placeholder: "Enter Description" %>
        </div>
        <div class="form-group">
            <label>Category</label>
            <%= f.text_field :category, class: "form-control", placeholder: "Enter Category" %>
          </div>

        <%= f.submit "Submit Changes", class: "btn btn-warning" %>
      <% end %>
    </div>
  </div>

app/views/images/index.html.erb
<% @images.each do |i| %>
<% if logged_in? %>

  <div class="home-wrapper">
    <div class="home-image">
        <%= image_tag(i.file.url) %>
    </div>

    <div class="home-image-info">
        <div class="home-image-username">
        <p><%= link_to i.user.username, user_path(i.user_id)%></p>
      </div>
      <div class="home-image-title">
        <p><%= i.title%></p>
      </div>
      <div class="home-image-description">
        <p><%= i.description %></p>
      </div>
    </div>
  </div>
<%else%>
redirect_to pages_path
<%end%>
<% end %>

app/views/images/new.html.erb
 <div class="add-image-form">   
    <div class="row">
        <div class="col-md-6 offset-md-3 new-background">
          <h1>Add Image</h1>
          <%= form_for @image do |f| %>
            <div class="form-group">
              <label>Image URL</label>
              <%= f.file_field :file, class: "form-control", placeholder: "Enter URL" %>
            </div>
            <div class="form-group">
              <label>Date</label>
              <%= f.text_field :date, class: "form-control", placeholder: "Enter Date" %>
            </div>
            <div class="form-group">
              <label>Title</label>
              <%= f.text_field :title, class: "form-control", placeholder: "Enter Title" %>
            </div>
            <div class="form-group">
              <label>Description</label>
              <%= f.text_field :description, class: "form-control", placeholder: "Enter Description" %>
            </div>
            <div class="form-group">
                <label>Category</label>
                <%= f.text_field :category, class: "form-control", placeholder: "Enter Category" %>
              </div>

            <%= f.submit "Add Image", class: "btn btn-secondary" %>
          <% end %>
        </div>
      </div>
</div>

app/views/images/show.html.erb
<h1><%= @user.name %></h1>

<div class="current-image-spacer">

</div>
<div class="current-image-wrapper">
<div class="current-date-edit">
<div class="current-image-date">
    <%= @image.date %>
</div>
<%if @user == current_user%>
<div class="current-image-edit">
    <%= link_to("Edit", edit_image_path(@image.id),  class: "btn btn-secondary") %>
</div>
<%end%>
</div>
<div class="current-image">
    <%= image_tag(@image.file.url) %>
</div>

<div class="current-image-info">
    <!-- <div class="current-image-title">
        <li><%= @image.title %></li>
    </div>
    <div class="current-image-category">
        <li><%= @image.category %></li>
    </div> -->
    <div class="current-image-description">
        <%= @image.description %>
    </div>
</div>
</div>

app/views/images/update.html.erb
<h1>Images#update</h1>
<p>Find me in app/views/images/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProgressTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= render '/partials/flash' %>
      
      <%= render '/partials/nav' %>

      <div class="spacer">

      </div> 
      <%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<div class="about">
  <p class="quote">"Don't wait until you've reached your goal to be proud of yourself. Be proud of every step you take toward reaching that goal."
    - Unknown
  </p>
    <p class="about-body">Enjoy every step of the way to get to your goals with <b>Progress Tracker</b>. <br>
      Our app allows you to visually track your progress by uploading images to your profile.
      Progress Trackers are also able to view each other's profiles to see and get motivated by each other's progress process.
      In order to achieve anything new, you have to be committed to making progress. <%= link_to "Sign Up", new_user_path %> now and ensure this commitment.
    </p>
</div>

<div class="wrapper">
<% @images.each do |i| %>
    
    <div class="card card-index" style="width: 18rem;">
      <!-- <img class="card-img-top" src="<%# movie.img_url %>" alt="Card image cap"> -->
      <%= image_tag(i.file.url, class: "card-img-top") %>
    </div>

  <% end %>
</div>

app/views/partials/_flash.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%=key%>"> 
    <%= value %>
    </div>
    <%end%>

app/views/partials/_nav.html.erb
<div class="header">
    <span class="n">
        Progress Tracker
    </span>

<ul class="nav justify-content-end">
        <% if logged_in? %>
            <li class="nav-item">
                <%= link_to "Home", images_path, :class => "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Profile", user_path(current_user.id), :class => "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "All Users", users_path, :class => "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Sign Out", logout_path, {method: 'delete', :class => "nav-link"} %>
            </li>
            
            <div class="search-form">
                    <%= form_tag(users_path, method: "get") do %>
                        <%= text_field_tag :search, params[:search],size:"20x1", placeholder: "Search" %>
                        <%= submit_tag "Search", class: "btn btn-secondary", name: nil %>
                    <% end %>
                </div>
        <%else%>
            <li class="nav-item">
                <%= link_to "Log In", new_session_path, :class => "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "Sign Up", new_user_path, :class => "nav-link" %>
            </li>
        <%end%>
      </ul>
</div>

      

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<div class="row">
    <div class="col-md-6 offset-md-3 edit-background">
      <h1>Edit Profile</h1>
      <%= form_for @user do |f| %>
        <div class="form-group">
          <label>Name</label>
          <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
        </div>
        <div class="form-group">
            <label>Username</label>
            <%= f.text_field :username, class: "form-control", placeholder: "Username" %>
          </div>
        <div class="form-group">
          <label>Email</label>
          <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
          <label>Type Your Password or Change Password</label>
          <%= f.password_field :password, class: "form-control", placeholder: "Password or New Password" %>
          <small id="passHelp" class="form-text text-muted">Enter your password to confirm changes. If you're updating your password, password should contain at least 6 characters.</small>
        </div>
        <div class="form-group">
          <label>Confirm Your Password or New Password</label>
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
        </div>
        <%= f.submit "Submit Changes", class: "btn btn-warning" %>
            <%= link_to("Delete", user_path(@user.id), {method: 'delete', data: {confirm: "Are you sure?"}, class:"btn btn-danger" }) %>
      <% end %>
    </div>
  </div>

app/views/users/index.html.erb
<% if @users.blank? %>
    <h4><%= params[:search] %> does not match any user.</h4>    
<% end %>


<div class="users-list">
<ul>
    <% @users.each do |u| %>
       <li> <%=link_to u.name, user_path(u.id) %></li>
    <% end %>   
   </ul>
</div>

app/views/users/new.html.erb
<div class="row">
    <div class="col-md-6 offset-md-3 singup-background">
      <h1>Sign Up</h1>
      <%= form_for @user do |f| %>
        <div class="form-group">
          <label>Name</label>
          <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
        </div>
        <div class="form-group">
            <label>Username</label>
            <%= f.text_field :username, class: "form-control", placeholder: "Username" %>
          </div>
        <div class="form-group">
          <label>Email</label>
          <%= f.text_field :email, class: "form-control", placeholder: "Email" %>
          <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>
        <div class="form-group">
          <label>Password</label>
          <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
          <small id="passHelp" class="form-text text-muted">Password should contain at least 6 characters.</small>
        </div>
        <div class="form-group">
          <label>Confirm Password</label>
          <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Confirm Password" %>
        </div>
        <%= f.submit "Create Account", class: "btn btn-secondary" %>
      <% end %>
    </div>
  </div>

app/views/users/show.html.erb
<div class="profile-wrapper">
        <div class="profile-name">
                <%= @user.name %>
        </div>
    <div class="name-edit-add">
            
        <%if @user == current_user%>
            <div class="edit-profile-btn">
                <h3><%= link_to "Edit Profile", edit_user_path(@user.id), class: "btn btn-secondary" %></h3>
            </div>
        <%end%>
        <div class="add-img-btn">
            <% if @user == current_user %>
                <%= link_to "Add New Image", new_image_path, class: "btn btn-secondary" %>
            <% end %>
        </div>
    </div>
</div>
<div class="profile-image">
<% @user.images.each do |i| %>
    <div class="profile-each-image">
        <div class="profile-card" style="width: 18rem;">
            <div class="profile-date">
                <%= i.date %>
            </div>
            <div class="profile-image-wrap"> 
            <%= image_tag(i.file.url) %>
            </div> 
            <div class="card-body">
                <h4 class="card-category"><%= i.category %></h4>
                <h5 class="card-title"><%= i.title %></h5>
                <p class="card-text"> <%=link_to "Click Here", image_path(i.id)%> to learn about progress </p>
            </div>
        </div>
        <%if i.user == current_user%>
            <div class="edit-delete">
                <div class="edit-img-btn">
                    <%= link_to("Edit", edit_image_path(i.id),  class: "btn btn-secondary") %>
                </div>
                <div class="delete-img-btn">
                    <%= link_to("Delete", image_path(i.id), {method: 'delete', data: {confirm: "Are you sure?"}, class:"btn btn-danger" }) %>
                </div>
            </div>
        <%end%>
    </div>
<% end %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>